Update rectangular_button.dart
Driexus/SimpleMoneyTracker pull request #15
Opened 2024-01-06 22:13 UTC by skfareeduddin

The button color will turn to grey when clicked!

2024-01-06 22:14 UTC, skfareeduddin commented
This is my proposed solution to the issue.

2024-01-08 15:09 UTC, Driexus commented
Hello skfareeduddin,

I am sorry for not writing the needed task a bit better. I did not think anyone would try to fix it so thank you for your effort.
Unfortunately this was not the intended behavior. I have updated the task to better reflect the intended behavior. Feel free to continue working on it if you wish.

2024-01-08 15:16 UTC, Driexus requested changes

2024-01-08 15:16 UTC, Driexus commented on lib/ui/home/buttons/rectangular_button.dart
> +  late Color currentColor;
This should not be changed. Instead, the button color should turn greyish (keeping its original color though) when clicked and then reverted back to normal when is let go.

2024-01-08 19:46 UTC, skfareeduddin commented on lib/ui/home/buttons/rectangular_button.dart
> +  late Color currentColor;
Ok. I'll do the necessary changes.

2024-01-15 15:42 UTC, skfareeduddin commented
I updated the code in the patch-1 as you said. Now the button will turn grey when clicked and then turn back to its original color.

2024-01-20 12:43 UTC, Driexus reviewed
The solution should use ripple effects. I had updated the issue description, please check it out along with the links if you still wish to solve it.

2024-01-20 12:43 UTC, Driexus commented on lib/ui/home/buttons/rectangular_button.dart
> +      buttonColor = Colors.grey; // Change color to grey when clicked
As I mentioned this should never be changed

2024-01-20 12:43 UTC, Driexus commented on lib/ui/home/buttons/rectangular_button.dart
> +    Future.delayed(Duration(milliseconds: 500), () {
Adding delays on triggers is generally a bad practice causing unwanted behavior (when button remains pressed for example)

2024-02-14 19:31 UTC, closed without merging